name: CI

on:
  push:
    branches: [master]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    paths:
      - ".github/workflows/*.yml"
      - "src/**"
      - ".*"
      - "package*.json"
      - "tsconfig.json"
      - "webpack.*"
      - "!**.md"
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Setup Node.js environment"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: "Install vsce"
        run: |
          npm install @vscode/vsce

      - name: "Build release"
        run: |
          npx @vscode/vsce package

      - name: Upload release binaries
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./vsnote-*"]'

      - name: "(debug) Upload npm log"
        if: ${{ !success() }}
        uses: actions/upload-artifact@v4
        with:
          name: "npm-debug-log"
          path: "~/.npm/_logs"
