name: CI

on:
  push:
    branches: [master]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    paths:
      - ".github/workflows/*.yml"
      - "src/**"
      - ".*"
      - "package*.json"
      - "tsconfig.json"
      - "webpack.*"
      - "!**.md"
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Setup Node.js environment"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: "Build release"
        run: |
          npx vsce package --pre-release

          export NODE_ENV='development'
          npx vsce package --pre-release --out debug.vsix

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vsnote-${{ github.sha }}
          path: ./*.vsix

      # If the run failed, npm log may help to diagnose.
      - name: "(debug) Upload npm log"
        if: ${{ !success() }}
        uses: actions/upload-artifact@v4
        with:
          name: "npm-debug-log"
          path: "~/.npm/_logs"