name: release

on:
  push:
    branches: [main]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    paths:
      - ".github/workflows/*.yml"
      - "src/**"
      - ".*"
      - "package*.json"
      - "tsconfig.json"
      - "webpack.*"
      - "!**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: "Setup Node.js environment"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: "Install vsce"
        run: |
          npm install @vscode/vsce

      - name: "Build release"
        run: |
          npx @vscode/vsce package

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: vsnote*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: "(debug) Upload npm log"
        if: ${{ !success() }}
        uses: actions/upload-artifact@v4
        with:
          name: "npm-debug-log"
          path: "~/.npm/_logs"
